---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: kube-system





---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
   matchLabels:
     k8s-app: fluentd-logging
     version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        #image: fluent/fluentd-kubernetes-daemonset:elasticsearch
        image: fluent/fluentd-kubernetes-daemonset:v1.11.1-debian-elasticsearch7-1.3
        env:
         - name:  FLUENT_ELASTICSEARCH_HOST
           value: "elastic.k8s.devopsforlife.io" # Or the host of your elasticsearch server
         - name:  FLUENT_ELASTICSEARCH_PORT
           value: "80" # The port that your elasticsearch API is exposed on
         - name: FLUENT_ELASTICSEARCH_SCHEME
           value: "http" # Either HTTP or HTTPS.
         
         #- name: FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT
         #  value: "false"
         #- name: FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME
         #  value: "k8s-infra"

         - name: FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT
           value: "false"
         - name: FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME
           value: "k8s-infra"
         - name: FLUENT_ELASTICSEARCH_INCLUDE_TIMESTAMP
           value: "true"

         #- name: FLUENT_UID
         #  value: "0" # Either HTTP or HTTPS.
         - name: FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT
           value: "16" # Either HTTP or HTTPS.
         - name: FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL
           value: "1s" # Either HTTP or HTTPS.
         - name: FLUENT_ELASTICSEARCH_BUFFER_CHUNK_LIMIT_SIZE
           value: "10M" # Either HTTP or HTTPS.
         - name: FLUENT_ELASTICSEARCH_BUFFER_QUEUE_LIMIT_LENGTH
           value: "16" # Either HTTP or HTTPS.
         - name: FLUENT_ELASTICSEARCH_BUFFER_RETRY_MAX_INTERVAL
           value: "30" # Either HTTP or HTTPS.
         - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
           value: "false" # Either HTTP or HTTPS.
         # X-Pack Authentication
        # =====================
         - name: FLUENT_ELASTICSEARCH_USER
           value: "elastic"
         - name: FLUENT_ELASTICSEARCH_PASSWORD
           value: "1qazXSW@3edc"


         - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
           value: '["/var/log/containers/fluentd-*"]'

           # FLUENT_ELASTICSEARCH_SSL_VERIFY false
           # index_name "logstash"



        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

